#!/bin/bash

service="svc_process_sms_queue"
svc_path="/home/www-data/repos/smr_web/services"
total=7

to_add=$(($total-$(ps -ef  | grep "$service" | wc -l)))

if [ "$to_add" -gt "0" ]
then echo "SHOULD ADD PROCESS $to_add";

cd $svc_path;

for a in `seq $to_add`
do
  nohub python $service".py" &
done;

fi
