#!/bin/bash
service=svc_process_sms_queue
srv_path=/home/www-data/repos/smr_web/services

if (( $(ps -ef | grep -v grep | grep $service | wc -l) > 0 ))
then
echo "$service is running!!!"
else
cd $srv_path
python svc_process_sms_queue.py
fi